config/routes.rb
Financial::Application.routes.draw do
  resources :categories do
    get 'cate', :on => :member
  end

  resources :records do
    get 'month', :on => :collection
     get 'category', :on => :collection
  end

  resources :accounts

  get "home/index"

  root :to => 'home#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :category
  has_many   :categories
  has_many   :records

  validates :name, :presence => true

  scope :income, where(:id => 1)
  scope :outlay, where(:id => 2)
end

app/models/fund.rb
class Fund < ActiveRecord::Base
  belongs_to :account
  belongs_to :fundType
  has_one :fundType

  scope :current, lambda{|account| where(:account_id=> account).order('created_at desc')}

end

app/models/fund_type.rb
class FundType < ActiveRecord::Base
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :category

  validates :date, :presence => true
  validates :fee,  :presence => true

  scope :find_by_month, lambda{|month| where('date like ?', month + '%').order('date desc')}
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @accounts = Account.all
  end

  def new
    @account = Account.new
  end

    def create
    @account = Account.new(params[:account])

    if @account.save
      flash[:notice] = 'save_successful'
      redirect_to new_account_path
    else
      render action: "new"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  respond_to :html, :js

  def index
    @income = Category.income.first
    @outlay = Category.outlay.first
  end

  def new
    @category = Category.new
  end

  def cate
    if params[:id] == 1
      @options = Category.income.first.categories
    else
      @options = Category.outlay.first.categories
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   process_outlay
   process_account

  end

  private
  def process_outlay
    @outlays = []
    @sums = []
    Category.outlay.first.categories.each do |category|
      sum = 0
      records = category.records.find_by_month Time.now.strftime("%Y-%m")
      unless records.empty?
        records.each do |record|
          sum += record.fee
        end
      end
      category.categories.each do |sub_cate|
        records = sub_cate.records.find_by_month Time.now.strftime("%Y-%m")
        unless records.empty?
          records.each do |record|
            sum += record.fee
          end
        end
      end
      if sum != 0
        @outlays.push category.name
        @sums.push sum
      end
    end
  end

  private
  def process_account
    @accounts = []
    @amounts = []
    Account.all.each do |account|
      @accounts.push account.name
      @amounts.push balance account
    end
  end

   private
   def balance account
    fund = Fund.current(account.id).first
    return fund.nil? ? 0 : fund.amount
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  respond_to :html, :js

  def index
    @month = Time.now.strftime("%Y-%m")
    @records = Record.find_by_month(@month).paginate(:page => params[:page], :per_page => 15)
    records = Record.find_by_month(@month)
    @income_sum = income_sum records
    @outlay_sum = outlay_sum records
  end

  def month
    @month = params[:month] || Time.now.strftime("%Y-%m")
    @records = Record.find_by_month(@month).paginate(:page => params[:page], :per_page => 15)
    records = Record.find_by_month(@month)
    @income_sum = income_sum records
    @outlay_sum = outlay_sum records
  end

  def category
    @records = Record.all
  end

  def show
    @record = Record.find(params[:id])
  end

  def new
    @record = Record.new
  end

  def edit
    @record = Record.find(params[:id])
  end

  def create
    @record = Record.new(params[:record])

    if @record.save
      flash[:notice] = 'save_successful'
      redirect_to new_record_path
    else
      render action: "new"
    end
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @record = Record.find(params[:id])

    if @record.update_attributes(params[:record])
      redirect_to edit_record_path(@record), notice: 'Record was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    redirect_to(records_path)
  end

  private
  def income_sum records
    sum = 0
    unless records.nil? || records.empty?
      records.each do |record|
        sum += income record unless income(record).nil?
      end
    end
    return sum
  end

  private
  def outlay_sum records
    sum = 0
    unless records.nil? || records.empty?
      records.each do |record|
        sum += outlay record unless outlay(record).nil?
      end
    end
    return sum
  end

  private
  def income record
    cate = record.category
    until cate.category.nil?
      cate = cate.category
    end
    return cate.id==1 ? record.fee : nil
  end

  private
  def outlay record
    cate = record.category
    until cate.category.nil?
      cate = cate.category
    end
    return cate.id==2 ? record.fee : nil
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def balance account
    fund = Fund.current(account.id).first
    return fund.amount unless fund.nil?
  end

  def sum accounts
    sum = 0
    accounts.each do |account|
      sum += balance account unless balance(account).nil?
    end
    return sum
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class Array
    def sum
      inject(0) do |sum, x|
        sum + x
      end
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/records_helper.rb
# -*- coding: utf-8 -*-
module RecordsHelper
  def cate_name category
    if category.category.id==1 || category.category.id==2
      return category.name
    else
      return category.category.name + ' - ' + category.name
    end
  end

  def income record
    cate = record.category
    until cate.category.nil?
      cate = cate.category
    end
    return cate.id==1 ? record.fee : nil
  end

  def outlay record
    cate = record.category
    until cate.category.nil?
      cate = cate.category
    end
    return cate.id==2 ? record.fee : nil
  end

  def defaultDate
    return @record.date.nil? ? Time.now.strftime("%Y-%m-%d") : @record.date
  end

  def cate_list categories
    list = [];
    unless categories.nil? || categories.empty?
      categories.each do |cate|
        list.push cate
        unless cate.categories.empty?
          cate.categories.each do |sub_cate|
            sub_cate.name='&nbsp;&nbsp;&nbsp;'.concat(sub_cate.name).html_safe
            list.push sub_cate
          end
        end
      end
    end
    return list
  end
end

app/views/accounts/_form.html.haml
= form_for(@account) do |f|
  %table.rec_table
    %tr
      %td.right
        开户地：
      %td
        =f.text_field :location
    %tr
      %td.right{:width=>'20%'}
        %em
          *
        名称：
      %td=f.text_field :name

    %tr
      %td.right
        账号：
      %td
        =f.text_field :number

    %tr
      %td
      %td
        =f.submit "提交", :class=>'submit'

app/views/accounts/index.html.haml
-content_for :title, '银行账号列表'
.grid_12.subtitle
  =link_to '账号列表', accounts_path, :class=>'current'
  %span.spline
    |
  =link_to '新增账号', new_account_path

.grid_12.subtitle
  %div{:style=>'float:right'}
    %span.green
      总资产： #{number_to_currency(sum(@accounts), :unit => '￥')}


.grid_12
  -unless @accounts.empty?
    %ul.list
      %li.head
        %span 银行
        %span{:width=>'180px'} 账号
        %span 开户地
        %span 余额
        %span 操作
      -@accounts.each do |account|
        %li.body
          %span
            =account.name
          %span
            =account.number
          %span
            =account.location
          %span
            =number_to_currency(balance(account), :unit => '￥')
          %span.center

            =image_tag 'edit.png'
            =image_tag 'delete.png'

  -else
    .eInfo
      =image_tag 'exclamation.png'
      %p
        %span 无银行账号
        %br
        %span 请点击
        =link_to '新增账号', new_account_path
        %span 添加

app/views/accounts/new.html.haml
-content_for :title, '新增银行账号'
.grid_12.subtitle
  =link_to '账号列表', accounts_path
  %span.spline
    |
  =link_to '新增账号', new_account_path, :class=>'current'

=render 'form'

app/views/categories/_form.html.haml
= form_for(@category) do |f|
  %table.rec_table
    %tr
      %td.right{:width=>'20%'}
        %em
          *
        性质：
      %td
        =f.radio_button :category_id, 1
        收入
        &nbsp;&nbsp;&nbsp;
        =f.radio_button :category_id, 2
        支出

    %tr
      %td.right{:width=>'20%'}
        %em
          *
        项目名称：
      %td
        =f.text_field :name
    %tr
      %td.right
        从属于：
      %td
        = f.collection_select :category_id, Category.outlay.first.categories, :id, :name

    %tr
      %td
      %td
        =f.submit "提交", :class=>'submit'

:javascript
  $('input[type=radio]').click(function(){
    changeCate(this.value)
  })

  function changeCate(id){
    $.ajax({
      url: "/categories/" + id + "/cate",
      success: function(msg){
        //alert("#{@options}")
      }
    });
  }

app/views/categories/cate.js.haml
alert('aaaaaa')

app/views/categories/index.html.haml
.grid_12.subtitle
  =link_to '收支项目管理', 'javascript:void(0)', :class=>'current'
  %span.spline
    |
  =link_to '新增收支项目', new_category_path

.grid_6
  -unless @income.nil? || @income.categories.empty?
    %table.list
      %tr.title
        %td.center{:style=>'width:80%'} 收入项目
        %td.center 操作
      -@income.categories.each do |category|
        %tr.content
          %td
            =category.name
          %td.center
            =image_tag 'edit.png'
            =image_tag 'delete.png'
  -else
    .eInfo
      =image_tag 'exclamation.png'
      %p
        %span 无收入项目
        %br
        %span 请点击
        =link_to '新增收支项目', new_record_path
        %span 添加


.grid_6
  -unless @outlay.nil? || @outlay.categories.empty?
    %table.list
      %tr.title
        %td.center{:style=>'width:80%'} 支出项目
        %td.center 操作
      -@outlay.categories.each do |category|
        %tr.content{:style=>'background-color:#FEE4E2'}
          %td
            =category.name
          %td.center
            =image_tag 'edit.png'
            =image_tag 'delete.png'
        -unless category.categories.empty?
          -category.categories.each do |sub_cate|
            %tr.content{:style=>'background-color:#FEEEED'}
              %td
                &nbsp;&nbsp;&nbsp;&nbsp;
                =sub_cate.name
              %td.center
                =image_tag 'edit.png'
                =image_tag 'delete.png'


  -else
    .eInfo
      =image_tag 'exclamation.png'
      %p
        %span 无支出项目
        %br
        %span 请点击
        =link_to '新增收支项目', new_record_path
        %span 添加

app/views/categories/new.html.haml
.grid_12.subtitle
  =link_to '收支项目管理', categories_path
  %span.spline
    |
  =link_to '新增收支项目', new_category_path, :class=>'current'

=render 'form'

app/views/home/index.html.haml
-content_for :title, '首页'
=javascript_include_tag "/Highcharts-2.1.9/js/highcharts"
.container_12
  .grid_6.subtitle
    %span
      本月支出
    .red{:style=>'float:right'}
      总计： #{number_to_currency((eval @sums.join('+')), :unit => '￥')}
  .grid_6.subtitle
    .blue{:style=>'float:right'}
      总资产： #{number_to_currency((eval @amounts.join('+')), :unit => '￥')}
    银行信息

.container_12
  .grid_6
    #outlay{:style=>"width:100%; height:350px; margin: 4px auto"}
  .grid_6
    #accounts{:style=>"width:100%; height:350px; margin: 4px auto"}

:javascript
  function outlay_chart(){
    var outlay;
    outlay = new Highcharts.Chart({
          chart: {
              renderTo: 'outlay',
              defaultSeriesType: 'column',
              margin: [ 20, 50, 50, 50]
          },

          xAxis: {
              categories: #{@outlays},
              labels: {
                  rotation: -45,
                  align: 'right',
                  style: {
                       font: 'normal 13px Microsoft YaHei'
                  }
              }
          },
          title: {
              text:''
          },
          yAxis: {
              min: 0,
              title: {
                  text: 'Total fee'
              }
          },
          legend: {
              enabled: false
          },
          tooltip: {
              formatter: function() {
                  return '<b>'+ this.x +'</b><br/>'+ '￥ '+ Highcharts.numberFormat(this.y, 2);
              }
          },
          series: [{
            name: 'fee',
            data: #{@sums},
            dataLabels: {
                enabled: true,
                rotation: -0,
                color: '#FFFFFF',
                align: 'right',
                x: -3,
                y: 14,
                formatter: function() {
                    return this.y;
                },
                style: {
                    font: 'bold 11px Verdana, sans-serif'
                }
            }
        }],
        credits:{
          href: 'javascript:void(0)',
          text: ''
        }
      });
  }

  function accounts_chart(){
    var outlay;
    outlay = new Highcharts.Chart({
          chart: {
              renderTo: 'accounts',
              defaultSeriesType: 'column',
              margin: [ 20, 50, 50, 50]
          },

          xAxis: {
              categories: #{@accounts},
              labels: {
                  rotation: -45,
                  align: 'right',
                  style: {
                       font: 'normal 13px Microsoft YaHei'
                  }
              }
          },
          title: {
              text:''
          },
          yAxis: {
              min: 0,
              title: {
                  text: 'Total fee'
              }
          },
          legend: {
              enabled: false
          },
          tooltip: {
              formatter: function() {
                  return '<b>'+ this.x +'</b><br/>'+ '￥ '+ Highcharts.numberFormat(this.y, 2);
              }
          },
          series: [{
            name: 'fee',
            data: #{@amounts},
            dataLabels: {
                enabled: true,
                rotation: -0,
                color: '#FFFFFF',
                align: 'right',
                x: -5,
                y: 14,
                formatter: function() {
                    return this.y;
                },
                style: {
                    font: 'bold 11px Verdana, sans-serif'
                }
            }
        }],
        credits:{
          href: 'javascript:void(0)',
          text: ''
        }
      });
  }

  $(function() {
    outlay_chart()
    accounts_chart()

  });

app/views/layouts/application.html.haml
!!! XML
!!!
%head
  %title=yield :title
  =stylesheet_link_tag "application"
  =javascript_include_tag "application"
  =javascript_include_tag "/My97DatePicker/WdatePicker"
  =favicon_link_tag 'favicon1.ico'
  =csrf_meta_tags
%body
  #header
    .header_content
      %span 家庭财务管理

  #main_content.container_12
    #tabs4= render_navigation
    =yield

  #footer.container_12.center
    %span
      copyright 2010-2011, Presented by Robert

app/views/records/_form.html.haml
= form_for(@record) do |f|
  %table.rec_table
    %tr
      %td.right{:width=>'20%'}
        %em
          *
        收支日期：
      %td
        =f.text_field :date, :value=>defaultDate, :class=>'Wdate', :readonly=>'readonly', :onfocus=>"WdatePicker({lang:'zh-cn'})"
    %tr
      %td.right 备注：
      %td
        =f.text_field :remark

    %tr
      %td.right
        %em
          *
        收支项目：
      %td
        = radio_button_tag 'record_type', 'income', false
        收入
        = f.collection_select :category_id, cate_list(Category.income.first.categories), :id, :name
    %tr
      %td
      %td
        = radio_button_tag 'record_type', 'outlay', true
        支出
        = f.collection_select :category_id, cate_list(Category.outlay.first.categories), :id, :name
    %tr
      %td.right
        %em
          *
        金额：
      %td
        =f.text_field :fee
    %tr
      %td
      %td
        =f.submit "提交", :class=>'submit'

:javascript
  $('input[type=radio]').each(function(){
    $(this).click(function(){switchCate(this)})
  })

  function switchCate(obj){
    if(obj.value == 'income'){
      $('select').get(0).name = 'record[category_id]'
      $('select').get(1).name = ''
    }
    else{
      $('select').get(1).name = 'record[category_id]'
      $('select').get(0).name = ''
    }
  }

app/views/records/_list.html.haml
.grid_12.subtitle
  %span #{@month.split('-')[0]}年#{@month.split('-')[1]}月合计
  %div{:style=>'float:right'}
    %span.green
      收入：#{'￥ ' + @income_sum.to_s} &nbsp;&nbsp;
    %span.red
      支出：#{'￥ ' + @outlay_sum.to_s} &nbsp;&nbsp;
    %span.blue
      结余：#{'￥ ' + (@income_sum - @outlay_sum).to_s}

.grid_12
  -unless @records.empty?
    %table.list
      %tr.title
        %td{:width=>'20%'} 收支项目
        %td{:width=>'10%'} 日期
        %td{:width=>'20%'} 说明
        %td{:width=>'20%'} 收入金额
        %td{:width=>'20%'} 支出金额
        %td{:width=>'10%'} 操作
      -@records.each do |record|
        %tr.content
          %td
            =cate_name record.category
          %td
            =record.date
          %td
            =record.remark
          %td
            %span.green #{('￥ ' + income(record).to_s) unless income(record).nil?}
          %td
            %span.red #{('￥ ' + outlay(record).to_s) unless outlay(record).nil?}
          %td
            =link_to '&nbsp;&nbsp;&nbsp;&nbsp;'.html_safe, edit_record_path(record), :class=>'edit', :title => '编辑账单'
            =link_to '&nbsp;&nbsp;&nbsp;&nbsp;'.html_safe, record, :class=>'delete', :title => '删除账单', :method => 'delete', :confirm => '确定删除？'

    = will_paginate @records, :previous_label => '上一页', :next_label => '下一页'

  -else
    .eInfo
      =image_tag 'exclamation.png'
      %p
        %span 本月无收支记录
        %br
        %span 请点击
        =link_to '新增记录', new_record_path
        %span 添加

app/views/records/category.html.haml
.grid_12.subtitle
  =link_to '本月收支', records_path
  %span.spline
    |
  =link_to '按月份查看', month_records_path
  %span.spline
    |
  =link_to '按收支项目查看', category_records_path, :class=>'current'

.grid_12#filter
  =select_tag "month", options_from_collection_for_select(Category.all, "id", "name")
  从
  =text_field_tag 'date_start', nil, :class=>'Wdate', :readonly=>'readonly', :onfocus=>"WdatePicker({lang:'zh-cn'})"
  到
  =text_field_tag 'date_end', nil, :class=>'Wdate', :readonly=>'readonly', :onfocus=>"WdatePicker({lang:'zh-cn'})"
  %input.submit{:type=>'submit', :value=>'查看'}

.grid_12

app/views/records/edit.html.haml
.grid_12.subtitle
  =link_to '修改账单', records_path, :class=>'current'

= render 'form'

app/views/records/index.html.haml
-content_for :title, '我的账本'
.grid_12.subtitle
  =link_to '本月收支', records_path, :class=>'current'
  %span.spline
    |
  =link_to '按月份查看', month_records_path
  %span.spline
    |
  =link_to '按收支项目查看', category_records_path

= render 'list'

app/views/records/month.html.haml
-content_for :title, '账单查询'
.grid_12.subtitle
  =link_to '本月收支', records_path
  %span.spline
    |
  =link_to '按月份查看', month_records_path, :class=>'current'
  %span.spline
    |
  =link_to '按收支项目查看', category_records_path

.grid_12#filter
  = form_tag month_records_path, :method => :get do
    %span
      月份
      = text_field_tag 'month', @month, :class=>'Wdate', :readonly=>'readonly', :onfocus=>"WdatePicker({lang:'zh-cn', dateFmt:'yyyy-MM'})"
      = submit_tag '查看', :class=>'submit', :name => nil

= render 'list'

app/views/records/new.html.haml
-content_for :title, '新建账单'
=javascript_include_tag "records"
.grid_12
  -unless notice.nil?
    .notice
      =image_tag "tick.png"
      %p
        添加记录成功， 点击这里查看
        =link_to '本月账单', records_path

  -if @record.errors.any?
    .eInfo2
      %ul
        -@record.errors.messages.each do |msg|
          %li
            =msg

  = render 'form'

:javascript
  if($('.notice').length !=0){
    setTimeout('hideNotice()', 2500)
  }

  function hideNotice(){
    $('.notice').slideToggle();
  }